"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import {
  AlertTriangle,
  Calendar,
  Check,
  Coins,
  Download,
  Hourglass,
  Loader2,
  RefreshCcw,
  Search,
  X,
} from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import PageHeader from "@/components/admin/ui/PageHeader";
import StatCard from "@/components/admin/ui/StatCard";
import SectionCard from "@/components/admin/ui/SectionCard";
import EmptyState from "@/components/admin/ui/EmptyState";
import StatusPill from "@/components/admin/ui/StatusPill";
import DonutChart from "@/components/admin/charts/DonutChart";
import { getPayments, UNRECORDED_METHOD } from "@/lib/admin/payments";
import { formatDateTime, formatMoney, formatNumber } from "@/lib/admin/format";
import type { Transaction } from "@/types/admin";

/**
 * Payments.
 *
 * This screen previously showed a hundred rows generated by `Math.random()` on
 * every mount — John Doe and Jane Smith paying in USD and RUB through PayPal
 * and Stripe — under the heading "Total Revenue". None of it touched the
 * database, and the numbers changed on reload. It now reads the orders, which
 * are the payment record on this installation; see `lib/admin/payments.ts`.
 *
 * Revenue means settled money. The old totals summed every row regardless of
 * status, so failed and unpaid orders counted as income.
 *
 * Export writes a real CSV. It used to be a button that did nothing.
 */
const PAYMENT_VIEW: Record<string, { label: string; icon: any; tone: any }> = {
  success: { label: "Settled", icon: Check, tone: "done" },
  pending: { label: "Awaiting", icon: Hourglass, tone: "attention" },
  failed: { label: "Failed", icon: AlertTriangle, tone: "danger" },
  refunded: { label: "Refunded", icon: X, tone: "neutral" },
};

export default function AdminPaymentsPage() {
  const [payments, setPayments] = useState<Transaction[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [methodFilter, setMethodFilter] = useState("all");
  const [dateFilter, setDateFilter] = useState("all");

  const load = useCallback(async () => {
    setIsLoading(true);
    const { payments: fetched, error } = await getPayments();
    if (error) toast.error(error);
    setPayments(fetched);
    setIsLoading(false);
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const methods = useMemo(
    () => Array.from(new Set(payments.map((payment) => payment.paymentMethod))).sort(),
    [payments]
  );

  const filtered = useMemo(() => {
    const query = searchQuery.trim().toLowerCase();
    const since = startOf(dateFilter);

    return payments.filter((payment) => {
      if (statusFilter !== "all" && payment.status !== statusFilter) return false;
      if (methodFilter !== "all" && payment.paymentMethod !== methodFilter) return false;
      if (since && payment.date < since) return false;

      if (query) {
        const haystack =
          `${payment.orderNumber} ${payment.customer} ${payment.email}`.toLowerCase();
        if (!haystack.includes(query)) return false;
      }

      return true;
    });
  }, [payments, statusFilter, methodFilter, dateFilter, searchQuery]);

  const settled = payments.filter((payment) => payment.status === "success");
  const awaiting = payments.filter((payment) => payment.status === "pending");
  const failed = payments.filter((payment) => payment.status === "failed");
  const refunded = payments.filter((payment) => payment.status === "refunded");

  const sum = (rows: Transaction[]) => rows.reduce((total, row) => total + row.amount, 0);
  const currency = payments[0]?.currency ?? "ngn";

  const hasFilters =
    statusFilter !== "all" || methodFilter !== "all" || dateFilter !== "all" || Boolean(searchQuery);

  const clearFilters = () => {
    setStatusFilter("all");
    setMethodFilter("all");
    setDateFilter("all");
    setSearchQuery("");
  };

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="Selling"
        title="Payments"
        description="What each order was worth, whether the money arrived, and how."
        actions={
          <>
            <Button variant="outline" onClick={load} disabled={isLoading}>
              <RefreshCcw className={`mr-2 h-4 w-4 ${isLoading ? "animate-spin" : ""}`} />
              Refresh
            </Button>
            <Button
              variant="outline"
              onClick={() => exportCsv(filtered)}
              disabled={filtered.length === 0}
            >
              <Download className="mr-2 h-4 w-4" />
              Export CSV
            </Button>
          </>
        }
      />

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard
          label="Settled"
          value={formatMoney(sum(settled), currency)}
          hint={`${formatNumber(settled.length)} payments received`}
          icon={Coins}
        />
        <StatCard
          label="Awaiting payment"
          value={formatMoney(sum(awaiting), currency)}
          hint={`${formatNumber(awaiting.length)} orders unpaid`}
          tone={awaiting.length > 0 ? "attention" : "default"}
          icon={Hourglass}
        />
        <StatCard
          label="Refunded"
          value={formatMoney(sum(refunded), currency)}
          hint={`${formatNumber(refunded.length)} refunds`}
        />
        <StatCard
          label="Failed"
          value={formatNumber(failed.length)}
          hint={failed.length > 0 ? "worth chasing" : "none"}
          tone={failed.length > 0 ? "attention" : "default"}
          icon={AlertTriangle}
        />
      </div>

      {payments.length > 0 && (
        <SectionCard title="How customers pay">
          <DonutChart
            data={methods.map((method) => ({
              name: method,
              value: payments.filter((payment) => payment.paymentMethod === method).length,
            }))}
            totalLabel="Payments"
          />
          {methods.includes(UNRECORDED_METHOD) && (
            <p className="mt-4 max-w-[65ch] font-body text-xs text-ink-muted">
              Orders settled over WhatsApp or by transfer arrive with no payment method recorded.
              Setting one on the order makes this breakdown useful.
            </p>
          )}
        </SectionCard>
      )}

      {/* ----------------------------------------------------------- filters */}
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center">
        <div className="relative flex-1">
          <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-ink-faint" />
          <Input
            placeholder="Search by order number, customer or email…"
            value={searchQuery}
            onChange={(event) => setSearchQuery(event.target.value)}
            className="pl-10"
          />
        </div>

        <div className="flex flex-wrap gap-2">
          <Select value={dateFilter} onValueChange={setDateFilter}>
            <SelectTrigger className="w-[150px]">
              <Calendar className="mr-2 h-4 w-4 shrink-0 text-ink-faint" />
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All time</SelectItem>
              <SelectItem value="today">Today</SelectItem>
              <SelectItem value="week">Last 7 days</SelectItem>
              <SelectItem value="month">Last 30 days</SelectItem>
            </SelectContent>
          </Select>

          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-[150px]">
              <SelectValue placeholder="Any status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Any status</SelectItem>
              <SelectItem value="success">Settled</SelectItem>
              <SelectItem value="pending">Awaiting</SelectItem>
              <SelectItem value="failed">Failed</SelectItem>
              <SelectItem value="refunded">Refunded</SelectItem>
            </SelectContent>
          </Select>

          {methods.length > 1 && (
            <Select value={methodFilter} onValueChange={setMethodFilter}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Any method" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Any method</SelectItem>
                {methods.map((method) => (
                  <SelectItem key={method} value={method}>
                    {method}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}

          {hasFilters && (
            <Button variant="ghost" size="icon" onClick={clearFilters} title="Clear filters">
              <X className="h-4 w-4" />
            </Button>
          )}
        </div>
      </div>

      {/* ------------------------------------------------------------- table */}
      {isLoading ? (
        <div className="flex items-center justify-center gap-2 rounded-sm border border-dashed border-rule py-20 font-body text-sm text-ink-muted">
          <Loader2 className="h-4 w-4 animate-spin" />
          Loading payments…
        </div>
      ) : filtered.length === 0 ? (
        <EmptyState
          icon={Coins}
          title={hasFilters ? "No payments match those filters" : "No payments yet"}
          description={
            hasFilters
              ? "Try a wider date range, or clear the filters."
              : "Every order that is placed appears here with its payment state."
          }
          action={
            hasFilters ? (
              <Button variant="outline" onClick={clearFilters}>
                Clear filters
              </Button>
            ) : undefined
          }
        />
      ) : (
        <div className="overflow-hidden rounded-sm border border-rule bg-card">
          <div className="hidden border-b border-rule bg-wash/60 px-4 py-2.5 font-body text-[11px] uppercase tracking-[0.14em] text-ink-muted lg:grid lg:grid-cols-[minmax(0,2fr)_minmax(0,1.5fr)_minmax(0,1.2fr)_minmax(0,1fr)_minmax(0,1fr)] lg:gap-4">
            <span>Customer</span>
            <span>Date</span>
            <span>Method</span>
            <span className="text-right">Amount</span>
            <span>Status</span>
          </div>

          <ul className="divide-y divide-rule">
            {filtered.map((payment) => (
              <li key={`${payment.orderNumber}-${payment.id}`}>
                <Link
                  href="/admin/orders"
                  className="grid grid-cols-1 gap-3 px-4 py-3 transition-colors hover:bg-wash/50 lg:grid-cols-[minmax(0,2fr)_minmax(0,1.5fr)_minmax(0,1.2fr)_minmax(0,1fr)_minmax(0,1fr)] lg:items-center lg:gap-4"
                >
                  <span className="min-w-0">
                    <span className="block truncate font-body text-sm text-foreground">
                      {payment.customer}
                    </span>
                    <span className="block truncate font-body text-xs tabular-nums text-ink-muted">
                      {payment.orderNumber}
                    </span>
                  </span>

                  <span className="font-body text-sm tabular-nums text-ink-muted">
                    {formatDateTime(payment.date)}
                  </span>

                  <span className="font-body text-sm text-ink-muted">
                    {payment.paymentMethod === UNRECORDED_METHOD ? (
                      <span className="text-ink-muted">{UNRECORDED_METHOD}</span>
                    ) : (
                      payment.paymentMethod
                    )}
                  </span>

                  <span className="font-body text-sm font-medium tabular-nums text-foreground lg:text-right">
                    {formatMoney(payment.amount, payment.currency)}
                  </span>

                  <span>
                    <StatusPill status={payment.status} map={PAYMENT_VIEW} />
                  </span>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

function startOf(range: string): Date | null {
  if (range === "all") return null;
  const date = new Date();

  if (range === "today") {
    date.setHours(0, 0, 0, 0);
    return date;
  }
  if (range === "week") {
    date.setDate(date.getDate() - 7);
    return date;
  }
  if (range === "month") {
    date.setDate(date.getDate() - 30);
    return date;
  }
  return null;
}

/**
 * A real download, not a decorative button. Fields are quoted and internal
 * quotes doubled, so a customer named O'Brien or an address with a comma does
 * not shift every column after it.
 */
function exportCsv(rows: Transaction[]) {
  const header = ["Order", "Customer", "Email", "Date", "Method", "Amount", "Currency", "Status"];

  const body = rows.map((row) => [
    row.orderNumber,
    row.customer,
    row.email,
    row.date.toISOString(),
    row.paymentMethod,
    row.amount.toFixed(2),
    row.currency.toUpperCase(),
    PAYMENT_VIEW[row.status]?.label ?? row.status,
  ]);

  const csv = [header, ...body]
    .map((line) => line.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(","))
    .join("\r\n");

  const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8;" }));
  const link = document.createElement("a");
  link.href = url;
  link.download = `ramazah-payments-${new Date().toISOString().slice(0, 10)}.csv`;
  link.click();
  URL.revokeObjectURL(url);

  toast.success(`${rows.length} payments exported.`);
}
