"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import {
  AlertTriangle,
  Calendar,
  ChevronRight,
  Check,
  Coins,
  Download,
  Hourglass,
  Loader2,
  RefreshCcw,
  Search,
  X,
} from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import PageHeader from "@/components/admin/ui/PageHeader";
import StatCard from "@/components/admin/ui/StatCard";
import EmptyState from "@/components/admin/ui/EmptyState";
import StatusPill from "@/components/admin/ui/StatusPill";
import Pager from "@/components/ui/Pager";
import useDebounced from "@/hooks/useDebounced";
import { getPayments, getPaymentsForExport } from "@/lib/admin/payments";
import { getPaymentSummary, type PaymentSummary } from "@/lib/admin/summaries";
import { formatDateTime, formatMoney, formatNumber } from "@/lib/admin/format";
import type { Transaction } from "@/types/admin";

/**
 * Payments.
 *
 * This screen previously showed a hundred rows generated by `Math.random()` on
 * every mount — John Doe and Jane Smith paying in USD and RUB through PayPal
 * and Stripe — under the heading "Total Revenue". None of it touched the
 * database, and the numbers changed on reload. It now reads the orders, which
 * are the payment record on this installation; see `lib/admin/payments.ts`.
 *
 * Revenue means settled money. The old totals summed every row regardless of
 * status, so failed and unpaid orders counted as income.
 *
 * Export writes a real CSV. It used to be a button that did nothing — and now
 * that the table is paged, it deliberately does not export the page: it re-runs
 * the filters and exports everything they match. A CSV of the fifty rows you
 * can already see would be a worse button than the one that did nothing,
 * because the file looks complete.
 */
const PAYMENT_VIEW: Record<string, { label: string; icon: any; tone: any }> = {
  success: { label: "Settled", icon: Check, tone: "done" },
  pending: { label: "Awaiting", icon: Hourglass, tone: "attention" },
  failed: { label: "Failed", icon: AlertTriangle, tone: "danger" },
  refunded: { label: "Refunded", icon: X, tone: "neutral" },
};

export default function AdminPaymentsPage() {
  const [payments, setPayments] = useState<Transaction[]>([]);
  const [total, setTotal] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  const [exporting, setExporting] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [dateFilter, setDateFilter] = useState("all");
  const [page, setPage] = useState(1);
  const [summary, setSummary] = useState<PaymentSummary | null>(null);
  const [reloadKey, setReloadKey] = useState(0);

  const search = useDebounced(searchQuery);

  /** The filters as the query wants them, shared by the table and the export. */
  const query = useMemo(
    () => ({
      status: statusFilter === "all" ? undefined : statusFilter,
      since: startOf(dateFilter),
      search,
    }),
    [statusFilter, dateFilter, search]
  );

  const load = useCallback(async () => {
    setIsLoading(true);
    const { payments: fetched, total: matched, page: landed, error } =
      await getPayments({ ...query, page });

    if (error) toast.error(error);
    setPayments(fetched);
    setTotal(matched);
    // The page that came back, not the one asked for: narrowing a filter while
    // standing on page six asks for rows that are no longer there, and the
    // query falls back to the first page rather than erroring.
    if (landed !== page) setPage(landed);
    setIsLoading(false);
  }, [query, page, reloadKey]);

  useEffect(() => {
    load();
  }, [load]);

  // The cards are about the shop, not the filter, so they are fetched once
  // rather than on every page turn.
  useEffect(() => {
    getPaymentSummary().then(({ summary: totals, error: summaryError }) => {
      if (summaryError) {
        toast.error(summaryError);
        return;
      }
      setSummary(totals);
    });
  }, [reloadKey]);

  const applyFilter = (set: (value: string) => void) => (value: string) => {
    set(value);
    setPage(1);
  };

  const handleExport = async () => {
    setExporting(true);
    const { payments: rows, error } = await getPaymentsForExport(query);
    setExporting(false);

    if (error) {
      toast.error(error);
      return;
    }
    exportCsv(rows);
  };

  // The cards describe the shop, not the filter: how much money is outstanding
  // does not change because you narrowed the table to last week.
  const settledTotal = summary?.successTotal ?? 0;
  const awaitingTotal = summary?.pendingTotal ?? 0;
  const refundedTotal = summary?.refundedTotal ?? 0;
  const awaitingCount = summary?.pending ?? 0;
  const failedCount = summary?.failed ?? 0;
  const oldestWait = summary?.oldestWait ?? null;
  const currency = summary?.currency ?? "ngn";

  const hasFilters =
    statusFilter !== "all" || dateFilter !== "all" || Boolean(searchQuery);

  const clearFilters = () => {
    setStatusFilter("all");
    setDateFilter("all");
    setSearchQuery("");
    setPage(1);
  };

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="Selling"
        title="Payments"
        description="What each order was worth, whether the money arrived, and how."
        actions={
          <>
            <Button
              variant="outline"
              onClick={() => setReloadKey((key) => key + 1)}
              disabled={isLoading}
            >
              <RefreshCcw className={`mr-2 h-4 w-4 ${isLoading ? "animate-spin" : ""}`} />
              Refresh
            </Button>
            <Button
              variant="outline"
              onClick={handleExport}
              disabled={exporting || total === 0}
            >
              <Download className="mr-2 h-4 w-4" />
              Export CSV
            </Button>
          </>
        }
      />

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard
          label="Settled"
          value={formatMoney(settledTotal, currency)}
          hint={`${formatNumber(summary?.success ?? 0)} payments received`}
          icon={Coins}
        />
        <StatCard
          label="Awaiting payment"
          value={formatMoney(awaitingTotal, currency)}
          hint={`${formatNumber(awaitingCount)} orders unpaid`}
          tone={awaitingCount > 0 ? "attention" : "default"}
          icon={Hourglass}
        />
        <StatCard
          label="Refunded"
          value={formatMoney(refundedTotal, currency)}
          hint={`${formatNumber(summary?.refunded ?? 0)} refunds`}
        />
        {/* Was a bare count of failed payments, which on a transfer shop is
            almost always zero. The actionable number is how long the oldest
            unpaid order has been sitting. */}
        <StatCard
          label="Longest wait"
          value={oldestWait === null ? "—" : `${oldestWait} ${oldestWait === 1 ? "day" : "days"}`}
          hint={
            oldestWait === null
              ? "nothing outstanding"
              : failedCount > 0
                ? `${formatNumber(failedCount)} failed as well`
                : "oldest unpaid order"
          }
          tone={oldestWait !== null && oldestWait >= 7 ? "attention" : "default"}
          icon={AlertTriangle}
        />
      </div>

      {/* ----------------------------------------------------------- filters */}
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center">
        <div className="relative flex-1">
          <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-ink-faint" />
          <Input
            placeholder="Search by order number, customer or email…"
            value={searchQuery}
            onChange={(event) => applyFilter(setSearchQuery)(event.target.value)}
            className="pl-10"
          />
        </div>

        <div className="flex flex-wrap gap-2">
          <Select value={dateFilter} onValueChange={applyFilter(setDateFilter)}>
            <SelectTrigger className="w-[150px]">
              <Calendar className="mr-2 h-4 w-4 shrink-0 text-ink-faint" />
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All time</SelectItem>
              <SelectItem value="today">Today</SelectItem>
              <SelectItem value="week">Last 7 days</SelectItem>
              <SelectItem value="month">Last 30 days</SelectItem>
            </SelectContent>
          </Select>

          <Select value={statusFilter} onValueChange={applyFilter(setStatusFilter)}>
            <SelectTrigger className="w-[150px]">
              <SelectValue placeholder="Any status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Any status</SelectItem>
              <SelectItem value="success">Settled</SelectItem>
              <SelectItem value="pending">Awaiting</SelectItem>
              <SelectItem value="failed">Failed</SelectItem>
              <SelectItem value="refunded">Refunded</SelectItem>
            </SelectContent>
          </Select>

          {hasFilters && (
            <Button variant="ghost" size="icon" onClick={clearFilters} title="Clear filters">
              <X className="h-4 w-4" />
            </Button>
          )}
        </div>
      </div>

      {/* ------------------------------------------------------------- table */}
      {isLoading ? (
        <div className="flex items-center justify-center gap-2 rounded-sm border border-dashed border-rule py-20 font-body text-sm text-ink-muted">
          <Loader2 className="h-4 w-4 animate-spin" />
          Loading payments…
        </div>
      ) : payments.length === 0 ? (
        <EmptyState
          icon={Coins}
          title={hasFilters ? "No payments match those filters" : "No payments yet"}
          description={
            hasFilters
              ? "Try a wider date range, or clear the filters."
              : "Every order that is placed appears here with its payment state."
          }
          action={
            hasFilters ? (
              <Button variant="outline" onClick={clearFilters}>
                Clear filters
              </Button>
            ) : undefined
          }
        />
      ) : (
        <div className="overflow-hidden rounded-sm border border-rule bg-card">
          {/* Five headings sat over four cells after the Method column was
              removed, so Amount printed under "Method". Waiting takes the slot:
              in a shop paid by transfer it is the only figure anyone acts on. */}
          <div className="hidden border-b border-rule bg-wash/60 px-4 py-2.5 font-body text-[11px] uppercase tracking-[0.14em] text-ink-muted lg:grid lg:grid-cols-[minmax(0,2fr)_minmax(0,1.4fr)_minmax(0,1fr)_minmax(0,1fr)_minmax(0,1.1fr)] lg:gap-4">
            <span>Customer</span>
            <span>Date</span>
            <span>Waiting</span>
            <span className="text-right">Amount</span>
            <span>Status</span>
          </div>

          <ul className="divide-y divide-rule">
            {payments.map((payment) => (
              <li key={`${payment.orderNumber}-${payment.id}`}>
                <Link
                  href={`/admin/orders/${payment.orderId}`}
                  className="group grid grid-cols-1 gap-3 px-4 py-3 transition-colors hover:bg-wash/50 lg:grid-cols-[minmax(0,2fr)_minmax(0,1.4fr)_minmax(0,1fr)_minmax(0,1fr)_minmax(0,1.1fr)] lg:items-center lg:gap-4"
                >
                  <span className="min-w-0">
                    <span className="block truncate font-body text-sm text-foreground">
                      {payment.customer}
                    </span>
                    <span className="block truncate font-body text-xs tabular-nums text-ink-muted">
                      {payment.orderNumber}
                    </span>
                  </span>

                  <span className="font-body text-sm tabular-nums text-ink-muted">
                    {formatDateTime(payment.date)}
                  </span>

                  <Waiting payment={payment} />

                  <span className="font-body text-sm font-medium tabular-nums text-foreground lg:text-right">
                    {formatMoney(payment.amount, payment.currency)}
                  </span>

                  <span className="flex items-center justify-between gap-2">
                    <StatusPill status={payment.status} map={PAYMENT_VIEW} />
                    <ChevronRight className="hidden h-4 w-4 shrink-0 text-ink-faint transition-transform group-hover:translate-x-0.5 lg:block" />
                  </span>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      )}

      {payments.length > 0 && (
        <Pager page={page} total={total} busy={isLoading} onChange={setPage} noun="payments" />
      )}
    </div>
  );
}

/**
 * How long an unpaid order has been unpaid.
 *
 * The number this screen exists to surface. Every order here is settled by bank
 * transfer against an invoice, so an unpaid one is not a failed payment — it is
 * a customer who has not got round to it, and the only thing to do about it is
 * chase them. A week is the point at which it stops being normal.
 *
 * Settled rows show when the money landed instead, which is the equivalent fact
 * for them.
 */
function Waiting({ payment }: { payment: Transaction }) {
  if (payment.status !== "pending") {
    return <span className="font-body text-sm text-ink-faint">—</span>;
  }

  const since = payment.placedAt ?? payment.date;
  const days = Math.floor((Date.now() - since.getTime()) / 86_400_000);
  const late = days >= 7;

  return (
    <span
      className={`font-body text-sm tabular-nums ${
        late ? "font-medium text-terra-ink" : "text-ink-muted"
      }`}
      title={late ? "Waiting over a week — worth chasing" : undefined}
    >
      {days === 0 ? "today" : `${days} ${days === 1 ? "day" : "days"}`}
    </span>
  );
}

function startOf(range: string): Date | null {
  if (range === "all") return null;
  const date = new Date();

  if (range === "today") {
    date.setHours(0, 0, 0, 0);
    return date;
  }
  if (range === "week") {
    date.setDate(date.getDate() - 7);
    return date;
  }
  if (range === "month") {
    date.setDate(date.getDate() - 30);
    return date;
  }
  return null;
}

/**
 * A real download, not a decorative button. Fields are quoted and internal
 * quotes doubled, so a customer named O'Brien or an address with a comma does
 * not shift every column after it.
 */
function exportCsv(rows: Transaction[]) {
  const header = ["Order", "Customer", "Email", "Date", "Amount", "Currency", "Status"];

  const body = rows.map((row) => [
    row.orderNumber,
    row.customer,
    row.email,
    row.date.toISOString(),
    row.amount.toFixed(2),
    row.currency.toUpperCase(),
    PAYMENT_VIEW[row.status]?.label ?? row.status,
  ]);

  const csv = [header, ...body]
    .map((line) => line.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(","))
    .join("\r\n");

  const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8;" }));
  const link = document.createElement("a");
  link.href = url;
  link.download = `ramazah-payments-${new Date().toISOString().slice(0, 10)}.csv`;
  link.click();
  URL.revokeObjectURL(url);

  toast.success(`${rows.length} payments exported.`);
}
